export const DATAREQUEST = "DATAREQUEST";
export const DATASUCCESS = "DATASUCCESS";
export const DATAERROR = "DATAERROR";
export const FILTERDATAREQUEST = "FILTERDATAREQUEST";
export const FILTERDATASUCCESS = "FILTERDATASUCCESS";
export const FILTERDATAERROR = "FILTERDATAERROR";
